services:
  proxy:
    image: nginx:1.29-alpine
    ports:
      - "127.0.0.1:8080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../../build/step-06/nginx:/etc/nginx/conf.d:ro
