spring.application.name=availability
app.version=${APP_VERSION:v1}
app.instance-id=${INSTANCE_ID:local}
external-api.base-url=${EXTERNAL_API_BASE_URL:http://localhost:9091}
spring.autoconfigure.exclude=org.springframework.boot.session.autoconfigure.SessionAutoConfiguration,org.springframework.boot.session.data.redis.autoconfigure.SessionDataRedisAutoConfiguration
